# Generated by Django 5.0.4 on 2025-06-30 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('is_unique_visitor', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('time_on_page', models.PositiveIntegerField(blank=True, help_text='Time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_session_duration', models.PositiveIntegerField(default=0, help_text='Average session duration in seconds')),
                ('most_viewed_page', models.URLField(blank=True)),
                ('most_viewed_project', models.CharField(blank=True, max_length=200)),
                ('most_viewed_blog_post', models.CharField(blank=True, max_length=200)),
                ('contact_form_submissions', models.PositiveIntegerField(default=0)),
                ('newsletter_signups', models.PositiveIntegerField(default=0)),
                ('project_views', models.PositiveIntegerField(default=0)),
                ('blog_post_views', models.PositiveIntegerField(default=0)),
                ('top_countries', models.JSONField(blank=True, default=list)),
                ('top_cities', models.JSONField(blank=True, default=list)),
                ('desktop_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mobile_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tablet_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('top_referrers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Metrics',
                'verbose_name_plural': 'Portfolio Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.CharField(max_length=200, unique=True)),
                ('project_title', models.CharField(max_length=200)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('avg_time_on_page', models.PositiveIntegerField(default=0, help_text='Average time in seconds')),
                ('github_clicks', models.PositiveIntegerField(default=0)),
                ('demo_clicks', models.PositiveIntegerField(default=0)),
                ('documentation_clicks', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('contact_inquiries', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Analytics',
                'verbose_name_plural': 'Project Analytics',
                'ordering': ['-total_views'],
            },
        ),
        migrations.CreateModel(
            name='SkillAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('project_associations', models.PositiveIntegerField(default=0)),
                ('blog_mentions', models.PositiveIntegerField(default=0)),
                ('proficiency_changes', models.JSONField(blank=True, default=list)),
                ('certification_dates', models.JSONField(blank=True, default=list)),
                ('job_market_demand', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Analytics',
                'verbose_name_plural': 'Skill Analytics',
                'ordering': ['-page_views'],
            },
        ),
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('share', 'Share'), ('download', 'Download'), ('click', 'Click'), ('comment', 'Comment')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_id', models.CharField(max_length=100)),
                ('interaction_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Interaction',
                'verbose_name_plural': 'Content Interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
