# Generated by Django 5.0.4 on 2025-07-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_hours',
            field=models.CharField(blank=True, help_text='e.g., Mon-Fri 9AM-5PM', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Physical address for footer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email for footer', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone for footer', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_url',
            field=models.URLField(blank=True, help_text='Discord server URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skype_username',
            field=models.CharField(blank=True, help_text='Skype username', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Telegram contact URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kaggle_url',
            field=models.URLField(blank=True, help_text='Kaggle profile URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
    ]
